<?php

namespace Security\nonces;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-06 at 14:10:34.
 */
class NonceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Nonce
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Nonce();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Security\nonces\Nonce::__get
     */
    public function test__get()
    {
        $testval = 'ab23cd56';
        $this->object->token = $testval;
        $this->assertEquals($testval, $this->object->token);
    }

    /**
     * @covers Security\nonces\Nonce::__set
     */
    public function test__set()
    {
        $testval = 'ab23cd56';
        $testtime = 123456;
        $this->object->token = $testval;
        $this->object->time = $testtime;
        $this->assertAttributeEquals($testval, 'token', $this->object);
        $this->assertAttributeEquals($testtime, 'time', $this->object);
    }

    /**
     * @covers Security\nonces\Nonce::__set
     * @expectedException \Exception
     */
    public function test__SetExceptsOnTooLongToken()
    {
        $this->object->token = "qqqqwljldjfljalsdflkjelfflkj[ljerlkje"
                . "lfjselfjdlkfjdlfjdlkjglkfjgflkjgsldfgjslfgjkdjfjdljflk"
                . "djfldflkfjlkdjgljgljglejelkfjeljelkjfljefljelfjsljeflej"
                . "flejflejffeljelfj";
    }

    /**
     * @covers Security\nonces\Nonce::__set
     * @expectedException \Exception
     */
    public function test__SetExceptsOnNonIntegerTime()
    {
        $this->object->time = 'cat';
    }

}
