<?php

namespace Security\nonces;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-06 at 14:35:28.
 */
class NonceMakerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NonceMaker
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NonceMaker();
        $this->nonce = new Nonce();
        $this->session_handler = new INonceSessionHandlerMock();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

//    /**
//     * @covers Security\nonces\NonceMaker::set_logger
//     * @todo   Implement testSet_logger().
//     */
//    public function testSet_logger() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Security\nonces\NonceMaker::set_session_handler
     */
    public function testSet_session_handler()
    {
        $this->object->set_session_handler($this->session_handler);
        $this->assertAttributeInstanceOf('\Security\nonces\INonceSessionHandler', 'session_handler', $this->object);
    }

    /**
     * @covers Security\nonces\NonceMaker::createNonceToken
     */
    public function testCreateNonceToken()
    {
        $result = $this->object->createNonceToken();
        $this->assertTrue(mb_strlen($result) <= \Security\nonces\Nonce::MAX_LENGTH);
    }

    /**
     * @covers Security\nonces\NonceMaker::make_form_field
     */
    public function testMake_form_field()
    {
        $testval = 'qwer1234';
        $pagename = 'testpage';
        $this->nonce->token = $testval;
        $this->expectOutputString("<input type='hidden' id='formToken' name='formToken' data='{$pagename}' value='{$this->nonce->token}' />");
        $this->object->make_form_field($this->nonce, $pagename);
    }

    /**
     * @covers Security\nonces\NonceMaker::createNonce
     */
    public function testCreateNonce()
    {
        $this->session_handler->set_response(true);
        $this->object->set_session_handler($this->session_handler);
        $this->object->createNonce('jip');
        $result = \ob_get_contents();
        $ex = "<input type='hidden' id='formToken' name='formToken' data='jip' value='";
        $this->assertEquals($ex, substr($result, 0, 71));
    }

}
