@startuml
System --> Agent: Generates request with unique values
System --> Patient: Generates unique request
System -> Agent: Sends request
System --> Patient: Sends request
Patient ->System: Logs on
Agent -> System: Logs on
Agent -> System: Does responses
Patient -> System: Does responses
Agent -> System: Does prayer
System --> Patient: Notifies that prayed for



@enduml