@startuml

start
:User arrives with hash;
if (hash is syntactically valid?) then (no)
  :error handling;
  stop
else (yes)
    if(hash is expired) then (yes)
        :late response handling;
        stop
    else(no)
        :load record;
        :load assignment;
        if(pain assessment required?) then (yes)
            fork
                :handle pain questions;
            fork again
                :assignment handling;
            end fork
        else (no)
            if(assignment present?) then (yes)
                :assignment handling;
            endif
        endif
    endif
        :completed;
  stop
endif

@enduml